# frozen_string_literal: true

source "https://rubygems.org"
gemspec

gem "rake", "~> 13.0"
gem "rspec", "~> 3.12"
gem "rubocop", "~> 1.48"
gem "rubocop-packaging", "~> 0.5.2"
gem "rubocop-performance", "~> 1.16"
gem "rubocop-rake", "~> 0.6.0"
gem "rubocop-rspec", "~> 2.19"
