# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in vosk.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21"
gem "rubocop-rake", "~> 0.7.1"
gem "rubocop-rspec", "~> 3.9"

gem "wavefile", "~> 1.1"

gem "webmock", "~> 3.26"
