# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"
require "rake/clean"
require "rubocop/rake_task"

CLEAN.include "pkg", "vosk-model-small-en-us-0.15"

RSpec::Core::RakeTask.new(:spec)

RuboCop::RakeTask.new(:lint)

task default: %i[build lint spec]
