# Generated by ffi_gen. Please do not change this file by hand.

require 'ffi'

module Vosk
  extend FFI::Library
  ffi_lib ["/home/vladimir/vosk-api/vosk/libvosk.so", "vosk"]
  
  def self.attach_function(name, *_)
    begin; super; rescue FFI::NotFoundError => e
      (class << self; self; end).class_eval { define_method(name) { |*_| raise e } }
    end
  end
  
  # Model stores all the data required for recognition
  #  it contains static data and can be shared across processing
  #  threads.
  class VoskModel < FFI::Struct
    layout :dummy, :char
  end
  
  # Speaker model is the same as model but contains the data
  #  for speaker identification.
  class VoskSpkModel < FFI::Struct
    layout :dummy, :char
  end
  
  # Recognizer object is the main object which processes data.
  #  Each recognizer usually runs in own thread and takes audio as input.
  #  Once audio is processed recognizer returns JSON object as a string
  #  which represent decoded information - words, confidences, times, n-best lists,
  #  speaker information and so on
  class VoskRecognizer < FFI::Struct
    layout :dummy, :char
  end
  
  # Inverse text normalization
  class VoskTextProcessor < FFI::Struct
    layout :dummy, :char
  end
  
  # Batch model object
  class VoskBatchModel < FFI::Struct
    layout :dummy, :char
  end
  
  # Batch recognizer object
  class VoskBatchRecognizer < FFI::Struct
    layout :dummy, :char
  end
  
  # Loads model data from the file and returns the model object
  # 
  # @param model_path: the path of the model on the filesystem
  # @returns model object or NULL if problem occured
  # 
  # @method model_new(model_path)
  # @param [String] model_path 
  # @return [VoskModel] 
  # @scope class
  attach_function :model_new, :vosk_model_new, [:string], VoskModel
  
  # Releases the model memory
  # 
  #  The model object is reference-counted so if some recognizer
  #  depends on this model, model might still stay alive. When
  #  last recognizer is released, model will be released too.
  # 
  # @method model_free(model)
  # @param [VoskModel] model 
  # @return [nil] 
  # @scope class
  attach_function :model_free, :vosk_model_free, [VoskModel], :void
  
  # Check if a word can be recognized by the model
  # @param word: the word
  # @returns the word symbol if @param word exists inside the model
  # or -1 otherwise.
  # Reminding that word symbol 0 is for <epsilon>
  # 
  # @method model_find_word(model, word)
  # @param [VoskModel] model 
  # @param [String] word 
  # @return [Integer] 
  # @scope class
  attach_function :model_find_word, :vosk_model_find_word, [VoskModel, :string], :int
  
  # Loads speaker model data from the file and returns the model object
  # 
  # @param model_path: the path of the model on the filesystem
  # @returns model object or NULL if problem occurred
  # 
  # @method spk_model_new(model_path)
  # @param [String] model_path 
  # @return [VoskSpkModel] 
  # @scope class
  attach_function :spk_model_new, :vosk_spk_model_new, [:string], VoskSpkModel
  
  # Releases the model memory
  # 
  #  The model object is reference-counted so if some recognizer
  #  depends on this model, model might still stay alive. When
  #  last recognizer is released, model will be released too.
  # 
  # @method spk_model_free(model)
  # @param [VoskSpkModel] model 
  # @return [nil] 
  # @scope class
  attach_function :spk_model_free, :vosk_spk_model_free, [VoskSpkModel], :void
  
  # Creates the recognizer object
  # 
  #  The recognizers process the speech and return text using shared model data
  #  @param model       VoskModel containing static data for recognizer. Model can be
  #                     shared across recognizers, even running in different threads.
  #  @param sample_rate The sample rate of the audio you going to feed into the recognizer.
  #                     Make sure this rate matches the audio content, it is a common
  #                     issue causing accuracy problems.
  #  @returns recognizer object or NULL if problem occured
  # 
  # @method recognizer_new(model, sample_rate)
  # @param [VoskModel] model 
  # @param [Float] sample_rate 
  # @return [VoskRecognizer] 
  # @scope class
  attach_function :recognizer_new, :vosk_recognizer_new, [VoskModel, :float], VoskRecognizer
  
  # Creates the recognizer object with speaker recognition
  # 
  #  With the speaker recognition mode the recognizer not just recognize
  #  text but also return speaker vectors one can use for speaker identification
  # 
  #  @param model       VoskModel containing static data for recognizer. Model can be
  #                     shared across recognizers, even running in different threads.
  #  @param sample_rate The sample rate of the audio you going to feed into the recognizer.
  #                     Make sure this rate matches the audio content, it is a common
  #                     issue causing accuracy problems.
  #  @param spk_model speaker model for speaker identification
  #  @returns recognizer object or NULL if problem occured
  # 
  # @method recognizer_new_spk(model, sample_rate, spk_model)
  # @param [VoskModel] model 
  # @param [Float] sample_rate 
  # @param [VoskSpkModel] spk_model 
  # @return [VoskRecognizer] 
  # @scope class
  attach_function :recognizer_new_spk, :vosk_recognizer_new_spk, [VoskModel, :float, VoskSpkModel], VoskRecognizer
  
  # Creates the recognizer object with the phrase list
  # 
  #  Sometimes when you want to improve recognition accuracy and when you don't need
  #  to recognize large vocabulary you can specify a list of phrases to recognize. This
  #  will improve recognizer speed and accuracy but might return (unk) if user said
  #  something different.
  # 
  #  Only recognizers with lookahead models support this type of quick configuration.
  #  Precompiled HCLG graph models are not supported.
  # 
  #  @param model       VoskModel containing static data for recognizer. Model can be
  #                     shared across recognizers, even running in different threads.
  #  @param sample_rate The sample rate of the audio you going to feed into the recognizer.
  #                     Make sure this rate matches the audio content, it is a common
  #                     issue causing accuracy problems.
  #  @param grammar The string with the list of phrases to recognize as JSON array of strings,
  #                 for example "("one two three four five", "(unk)")".
  # 
  #  @returns recognizer object or NULL if problem occured
  # 
  # @method recognizer_new_grm(model, sample_rate, grammar)
  # @param [VoskModel] model 
  # @param [Float] sample_rate 
  # @param [String] grammar 
  # @return [VoskRecognizer] 
  # @scope class
  attach_function :recognizer_new_grm, :vosk_recognizer_new_grm, [VoskModel, :float, :string], VoskRecognizer
  
  # Adds speaker model to already initialized recognizer
  # 
  # Can add speaker recognition model to already created recognizer. Helps to initialize
  # speaker recognition for grammar-based recognizer.
  # 
  # @param spk_model Speaker recognition model
  # 
  # @method recognizer_set_spk_model(recognizer, spk_model)
  # @param [VoskRecognizer] recognizer 
  # @param [VoskSpkModel] spk_model 
  # @return [nil] 
  # @scope class
  attach_function :recognizer_set_spk_model, :vosk_recognizer_set_spk_model, [VoskRecognizer, VoskSpkModel], :void
  
  # Reconfigures recognizer to use grammar
  # 
  # @param recognizer   Already running VoskRecognizer
  # @param grammar      Set of phrases in JSON array of strings or "()" to use default model graph.
  #                     See also vosk_recognizer_new_grm
  # 
  # @method recognizer_set_grm(recognizer, grammar)
  # @param [VoskRecognizer] recognizer 
  # @param [String] grammar 
  # @return [nil] 
  # @scope class
  attach_function :recognizer_set_grm, :vosk_recognizer_set_grm, [VoskRecognizer, :string], :void
  
  # Configures recognizer to output n-best results
  # 
  # <pre>
  #   {
  #      "alternatives": (
  #          { "text": "one two three four five", "confidence": 0.97 },
  #          { "text": "one two three for five", "confidence": 0.03 },
  #      )
  #   }
  # </pre>
  # 
  # @param max_alternatives - maximum alternatives to return from recognition results
  # 
  # @method recognizer_set_max_alternatives(recognizer, max_alternatives)
  # @param [VoskRecognizer] recognizer 
  # @param [Integer] max_alternatives 
  # @return [nil] 
  # @scope class
  attach_function :recognizer_set_max_alternatives, :vosk_recognizer_set_max_alternatives, [VoskRecognizer, :int], :void
  
  # Enables words with times in the output
  # 
  # <pre>
  #   "result" : ({
  #       "conf" : 1.000000,
  #       "end" : 1.110000,
  #       "start" : 0.870000,
  #       "word" : "what"
  #     }, {
  #       "conf" : 1.000000,
  #       "end" : 1.530000,
  #       "start" : 1.110000,
  #       "word" : "zero"
  #     }, {
  #       "conf" : 1.000000,
  #       "end" : 1.950000,
  #       "start" : 1.530000,
  #       "word" : "zero"
  #     }, {
  #       "conf" : 1.000000,
  #       "end" : 2.340000,
  #       "start" : 1.950000,
  #       "word" : "zero"
  #     }, {
  #       "conf" : 1.000000,
  #       "end" : 2.610000,
  #       "start" : 2.340000,
  #       "word" : "one"
  #     }),
  # </pre>
  # 
  # @param words - boolean value
  # 
  # @method recognizer_set_words(recognizer, words)
  # @param [VoskRecognizer] recognizer 
  # @param [Integer] words 
  # @return [nil] 
  # @scope class
  attach_function :recognizer_set_words, :vosk_recognizer_set_words, [VoskRecognizer, :int], :void
  
  # Like above return words and confidences in partial results
  # 
  # @param partial_words - boolean value
  # 
  # @method recognizer_set_partial_words(recognizer, partial_words)
  # @param [VoskRecognizer] recognizer 
  # @param [Integer] partial_words 
  # @return [nil] 
  # @scope class
  attach_function :recognizer_set_partial_words, :vosk_recognizer_set_partial_words, [VoskRecognizer, :int], :void
  
  # Set NLSML output
  # @param nlsml - boolean value
  # 
  # @method recognizer_set_nlsml(recognizer, nlsml)
  # @param [VoskRecognizer] recognizer 
  # @param [Integer] nlsml 
  # @return [nil] 
  # @scope class
  attach_function :recognizer_set_nlsml, :vosk_recognizer_set_nlsml, [VoskRecognizer, :int], :void
  
  # (Not documented)
  # 
  # <em>This entry is only for documentation and no real method. The FFI::Enum can be accessed via #enum_type(:vosk_ep_mode).</em>
  # 
  # === Options:
  # :answer_default ::
  #   
  # :answer_short ::
  #   
  # :answer_long ::
  #   
  # :answer_very_long ::
  #   
  # 
  # @method _enum_vosk_ep_mode_
  # @return [Symbol]
  # @scope class
  enum :vosk_ep_mode, [
    :answer_default, 0,
    :answer_short, 1,
    :answer_long, 2,
    :answer_very_long, 3
  ]
  
  # Set endpointer scaling factor
  # 
  # @param mode - Endpointer mode
  # 
  # @method recognizer_set_endpointer_mode(recognizer, mode)
  # @param [VoskRecognizer] recognizer 
  # @param [Symbol from _enum_vosk_ep_mode_] mode 
  # @return [nil] 
  # @scope class
  attach_function :recognizer_set_endpointer_mode, :vosk_recognizer_set_endpointer_mode, [VoskRecognizer, :vosk_ep_mode], :void
  
  # Set endpointer delays
  # 
  # @param t_start_max     timeout for stopping recognition in case of initial silence (usually around 5.0)
  # @param t_end           timeout for stopping recognition in milliseconds after we recognized something (usually around 0.5 - 1.0)
  # @param t_max           timeout for forcing utterance end in milliseconds (usually around 20-30)
  # 
  # @method recognizer_set_endpointer_delays(recognizer, t_start_max, t_end, t_max)
  # @param [VoskRecognizer] recognizer 
  # @param [Float] t_start_max 
  # @param [Float] t_end 
  # @param [Float] t_max 
  # @return [nil] 
  # @scope class
  attach_function :recognizer_set_endpointer_delays, :vosk_recognizer_set_endpointer_delays, [VoskRecognizer, :float, :float, :float], :void
  
  # Accept voice data
  # 
  #  accept and process new chunk of voice data
  # 
  #  @param data - audio data in PCM 16-bit mono format
  #  @param length - length of the audio data
  #  @returns 1 if silence is occured and you can retrieve a new utterance with result method 
  #           0 if decoding continues
  #           -1 if exception occured
  # 
  # @method recognizer_accept_waveform(recognizer, data, length)
  # @param [VoskRecognizer] recognizer 
  # @param [String] data 
  # @param [Integer] length 
  # @return [Integer] 
  # @scope class
  attach_function :recognizer_accept_waveform, :vosk_recognizer_accept_waveform, [VoskRecognizer, :string, :int], :int
  
  # Same as above but the version with the short data for language bindings where you have
  #  audio as array of shorts
  # 
  # @method recognizer_accept_waveform_s(recognizer, data, length)
  # @param [VoskRecognizer] recognizer 
  # @param [FFI::Pointer(*Short)] data 
  # @param [Integer] length 
  # @return [Integer] 
  # @scope class
  attach_function :recognizer_accept_waveform_s, :vosk_recognizer_accept_waveform_s, [VoskRecognizer, :pointer, :int], :int
  
  # Same as above but the version with the float data for language bindings where you have
  #  audio as array of floats
  # 
  # @method recognizer_accept_waveform_f(recognizer, data, length)
  # @param [VoskRecognizer] recognizer 
  # @param [FFI::Pointer(*Float)] data 
  # @param [Integer] length 
  # @return [Integer] 
  # @scope class
  attach_function :recognizer_accept_waveform_f, :vosk_recognizer_accept_waveform_f, [VoskRecognizer, :pointer, :int], :int
  
  # Returns speech recognition result
  # 
  # @returns the result in JSON format which contains decoded line, decoded
  #          words, times in seconds and confidences. You can parse this result
  #          with any json parser
  # 
  # <pre>
  #  {
  #    "text" : "what zero zero zero one"
  #  }
  # </pre>
  # 
  # If alternatives enabled it returns result with alternatives, see also vosk_recognizer_set_max_alternatives().
  # 
  # If word times enabled returns word time, see also vosk_recognizer_set_word_times().
  # 
  # @method recognizer_result(recognizer)
  # @param [VoskRecognizer] recognizer 
  # @return [String] 
  # @scope class
  attach_function :recognizer_result, :vosk_recognizer_result, [VoskRecognizer], :string
  
  # Returns partial speech recognition
  # 
  # @returns partial speech recognition text which is not yet finalized.
  #          result may change as recognizer process more data.
  # 
  # <pre>
  # {
  #    "partial" : "cyril one eight zero"
  # }
  # </pre>
  # 
  # @method recognizer_partial_result(recognizer)
  # @param [VoskRecognizer] recognizer 
  # @return [String] 
  # @scope class
  attach_function :recognizer_partial_result, :vosk_recognizer_partial_result, [VoskRecognizer], :string
  
  # Returns speech recognition result. Same as result, but doesn't wait for silence
  #  You usually call it in the end of the stream to get final bits of audio. It
  #  flushes the feature pipeline, so all remaining audio chunks got processed.
  # 
  #  @returns speech result in JSON format.
  # 
  # @method recognizer_final_result(recognizer)
  # @param [VoskRecognizer] recognizer 
  # @return [String] 
  # @scope class
  attach_function :recognizer_final_result, :vosk_recognizer_final_result, [VoskRecognizer], :string
  
  # Resets the recognizer
  # 
  #  Resets current results so the recognition can continue from scratch
  # 
  # @method recognizer_reset(recognizer)
  # @param [VoskRecognizer] recognizer 
  # @return [nil] 
  # @scope class
  attach_function :recognizer_reset, :vosk_recognizer_reset, [VoskRecognizer], :void
  
  # Releases recognizer object
  # 
  #  Underlying model is also unreferenced and if needed released
  # 
  # @method recognizer_free(recognizer)
  # @param [VoskRecognizer] recognizer 
  # @return [nil] 
  # @scope class
  attach_function :recognizer_free, :vosk_recognizer_free, [VoskRecognizer], :void
  
  # Set log level for Kaldi messages
  # 
  #  @param log_level the level
  #     0 - default value to print info and error messages but no debug
  #     less than 0 - don't print info messages
  #     greater than 0 - more verbose mode
  # 
  # @method set_log_level(log_level)
  # @param [Integer] log_level 
  # @return [nil] 
  # @scope class
  attach_function :set_log_level, :vosk_set_log_level, [:int], :void
  
  # Init, automatically select a CUDA device and allow multithreading.
  # Must be called once from the main thread.
  # Has no effect if HAVE_CUDA flag is not set.
  # 
  # @method gpu_init()
  # @return [nil] 
  # @scope class
  attach_function :gpu_init, :vosk_gpu_init, [], :void
  
  # Init CUDA device in a multi-threaded environment.
  # Must be called for each thread.
  # Has no effect if HAVE_CUDA flag is not set.
  # 
  # @method gpu_thread_init()
  # @return [nil] 
  # @scope class
  attach_function :gpu_thread_init, :vosk_gpu_thread_init, [], :void
  
  # Creates the batch recognizer object
  # 
  #  @returns model object or NULL if problem occured
  # 
  # @method batch_model_new(model_path)
  # @param [String] model_path 
  # @return [VoskBatchModel] 
  # @scope class
  attach_function :batch_model_new, :vosk_batch_model_new, [:string], VoskBatchModel
  
  # Releases batch model object
  # 
  # @method batch_model_free(model)
  # @param [VoskBatchModel] model 
  # @return [nil] 
  # @scope class
  attach_function :batch_model_free, :vosk_batch_model_free, [VoskBatchModel], :void
  
  # Wait for the processing
  # 
  # @method batch_model_wait(model)
  # @param [VoskBatchModel] model 
  # @return [nil] 
  # @scope class
  attach_function :batch_model_wait, :vosk_batch_model_wait, [VoskBatchModel], :void
  
  # Creates batch recognizer object
  #  @returns recognizer object or NULL if problem occured
  # 
  # @method batch_recognizer_new(model, sample_rate)
  # @param [VoskBatchModel] model 
  # @param [Float] sample_rate 
  # @return [VoskBatchRecognizer] 
  # @scope class
  attach_function :batch_recognizer_new, :vosk_batch_recognizer_new, [VoskBatchModel, :float], VoskBatchRecognizer
  
  # Releases batch recognizer object
  # 
  # @method batch_recognizer_free(recognizer)
  # @param [VoskBatchRecognizer] recognizer 
  # @return [nil] 
  # @scope class
  attach_function :batch_recognizer_free, :vosk_batch_recognizer_free, [VoskBatchRecognizer], :void
  
  # Accept batch voice data
  # 
  # @method batch_recognizer_accept_waveform(recognizer, data, length)
  # @param [VoskBatchRecognizer] recognizer 
  # @param [String] data 
  # @param [Integer] length 
  # @return [nil] 
  # @scope class
  attach_function :batch_recognizer_accept_waveform, :vosk_batch_recognizer_accept_waveform, [VoskBatchRecognizer, :string, :int], :void
  
  # Set NLSML output
  # @param nlsml - boolean value
  # 
  # @method batch_recognizer_set_nlsml(recognizer, nlsml)
  # @param [VoskBatchRecognizer] recognizer 
  # @param [Integer] nlsml 
  # @return [nil] 
  # @scope class
  attach_function :batch_recognizer_set_nlsml, :vosk_batch_recognizer_set_nlsml, [VoskBatchRecognizer, :int], :void
  
  # Closes the stream
  # 
  # @method batch_recognizer_finish_stream(recognizer)
  # @param [VoskBatchRecognizer] recognizer 
  # @return [nil] 
  # @scope class
  attach_function :batch_recognizer_finish_stream, :vosk_batch_recognizer_finish_stream, [VoskBatchRecognizer], :void
  
  # Return results
  # 
  # @method batch_recognizer_front_result(recognizer)
  # @param [VoskBatchRecognizer] recognizer 
  # @return [String] 
  # @scope class
  attach_function :batch_recognizer_front_result, :vosk_batch_recognizer_front_result, [VoskBatchRecognizer], :string
  
  # Release and free first retrieved result
  # 
  # @method batch_recognizer_pop(recognizer)
  # @param [VoskBatchRecognizer] recognizer 
  # @return [nil] 
  # @scope class
  attach_function :batch_recognizer_pop, :vosk_batch_recognizer_pop, [VoskBatchRecognizer], :void
  
  # Get amount of pending chunks for more intelligent waiting
  # 
  # @method batch_recognizer_get_pending_chunks(recognizer)
  # @param [VoskBatchRecognizer] recognizer 
  # @return [Integer] 
  # @scope class
  attach_function :batch_recognizer_get_pending_chunks, :vosk_batch_recognizer_get_pending_chunks, [VoskBatchRecognizer], :int
  
  # Create text processor
  # 
  # @method text_processor_new(tagger, verbalizer)
  # @param [String] tagger 
  # @param [String] verbalizer 
  # @return [VoskTextProcessor] 
  # @scope class
  attach_function :text_processor_new, :vosk_text_processor_new, [:string, :string], VoskTextProcessor
  
  # Release text processor
  # 
  # @method text_processor_free(processor)
  # @param [VoskTextProcessor] processor 
  # @return [nil] 
  # @scope class
  attach_function :text_processor_free, :vosk_text_processor_free, [VoskTextProcessor], :void
  
  # Convert string
  # 
  # @method text_processor_itn(processor, input)
  # @param [VoskTextProcessor] processor 
  # @param [String] input 
  # @return [String] 
  # @scope class
  attach_function :text_processor_itn, :vosk_text_processor_itn, [VoskTextProcessor, :string], :string
  
end
