# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in vosk.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21"

gem "pry-byebug", "3.10.1"

gem "pry", "0.14.2"
