# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

require "rubocop/rake_task"

RuboCop::RakeTask.new

# TODO: modify 'build' task somehow to include pre-compiled binary
# (or add this logic into gemspec)

task default: %i[spec rubocop]
